[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200

[profile.ci]
fuzz = { runs = 10000 }

[rpc_endpoints]
celo = "${CELO_RPC_URL}"
alfajores = "${ALFAJORES_RPC_URL}"

[etherscan]
celo = { key = "${CELOSCAN_API_KEY}" }
alfajores = { key = "${CELOSCAN_API_KEY}" }

